package com.daily.wallpaper.ui.theme

import androidx.compose.ui.graphics.Color

// ── Fallback Light Color Scheme (seed: #3A7CA5 teal-blue) ──
val md_primary_light = Color(0xFF00658E)
val md_on_primary_light = Color(0xFFFFFFFF)
val md_primary_container_light = Color(0xFFC5E7FF)
val md_on_primary_container_light = Color(0xFF001E2D)
val md_secondary_light = Color(0xFF4F616E)
val md_on_secondary_light = Color(0xFFFFFFFF)
val md_secondary_container_light = Color(0xFFD2E5F5)
val md_on_secondary_container_light = Color(0xFF0A1E29)
val md_tertiary_light = Color(0xFF5D5B7D)
val md_on_tertiary_light = Color(0xFFFFFFFF)
val md_tertiary_container_light = Color(0xFFE3E0FF)
val md_on_tertiary_container_light = Color(0xFF19173A)
val md_error_light = Color(0xFFBA1A1A)
val md_on_error_light = Color(0xFFFFFFFF)
val md_error_container_light = Color(0xFFFFDAD6)
val md_on_error_container_light = Color(0xFF410002)
val md_surface_light = Color(0xFFF6FAFD)
val md_on_surface_light = Color(0xFF191C1E)
val md_on_surface_variant_light = Color(0xFF41484D)
val md_outline_light = Color(0xFF71787E)
val md_outline_variant_light = Color(0xFFC1C7CE)
val md_surface_container_lowest_light = Color(0xFFFFFFFF)
val md_surface_container_low_light = Color(0xFFF0F4F8)
val md_surface_container_light = Color(0xFFEAEEF2)
val md_surface_container_high_light = Color(0xFFE4E9ED)
val md_surface_container_highest_light = Color(0xFFDFE3E7)
val md_inverse_surface_light = Color(0xFF2E3133)
val md_inverse_on_surface_light = Color(0xFFEFF1F3)
val md_inverse_primary_light = Color(0xFF7AD0FF)
val md_surface_dim_light = Color(0xFFD5DBDF)
val md_surface_bright_light = Color(0xFFF6FAFD)

// ── Fallback Dark Color Scheme ──
val md_primary_dark = Color(0xFF7AD0FF)
val md_on_primary_dark = Color(0xFF00344C)
val md_primary_container_dark = Color(0xFF004C6D)
val md_on_primary_container_dark = Color(0xFFC5E7FF)
val md_secondary_dark = Color(0xFFB6C9D8)
val md_on_secondary_dark = Color(0xFF20333F)
val md_secondary_container_dark = Color(0xFF374A56)
val md_on_secondary_container_dark = Color(0xFFD2E5F5)
val md_tertiary_dark = Color(0xFFC6C3EA)
val md_on_tertiary_dark = Color(0xFF2E2C4F)
val md_tertiary_container_dark = Color(0xFF454367)
val md_on_tertiary_container_dark = Color(0xFFE3E0FF)
val md_error_dark = Color(0xFFFFB4AB)
val md_on_error_dark = Color(0xFF690005)
val md_error_container_dark = Color(0xFF93000A)
val md_on_error_container_dark = Color(0xFFFFDAD6)
val md_surface_dark = Color(0xFF101416)
val md_on_surface_dark = Color(0xFFE0E3E5)
val md_on_surface_variant_dark = Color(0xFFC1C7CE)
val md_outline_dark = Color(0xFF8B9298)
val md_outline_variant_dark = Color(0xFF41484D)
val md_surface_container_lowest_dark = Color(0xFF0B0F11)
val md_surface_container_low_dark = Color(0xFF191C1E)
val md_surface_container_dark = Color(0xFF1D2022)
val md_surface_container_high_dark = Color(0xFF282A2C)
val md_surface_container_highest_dark = Color(0xFF333537)
val md_inverse_surface_dark = Color(0xFFE0E3E5)
val md_inverse_on_surface_dark = Color(0xFF191C1E)
val md_inverse_primary_dark = Color(0xFF00658E)
val md_surface_dim_dark = Color(0xFF101416)
val md_surface_bright_dark = Color(0xFF363A3C)
